### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by SmallTownSound** [jariseon/synergia#2]
Thanks for having me as a beta tester...  

First impressions are good, except with studio One 4.  Typical beta issues.

Works in Reaper (have it just to test plugins).

Standalone works fine, but really needs ASIO, so I can use my Quantum interface properly.

When loaded in Studio One 4 (haven't upgraded to 5, it locks up all VSTs.  Others loaded will not come up again after Synergi is loaded, and Synergia will not show on screen, will not show interface at all.  Tried reloading a couple of times.  Have a lot of VSTs loaded, and never had this issue with any, even older 32bit vsts using jbridge..  I will DL the ver 5 demo and see if it works there.,

The sounds DO sound like I remember, will play with it more this evening.  Love it for a beta version. 

One thing I noticed, that is starts without a preset selected, just annoying, not a problem.  If I remember correctly that didn't happen with the Synergy..  

Don

**Comment by jariseon** [comment]
thanks Don! Studio One 5 Prime seems to be free. i'll install it and check what's going on. will also add ASIO and default voice selection into the next beta release.

- [x] plugin does not load in Studio One
- [x] add ASIO to windows standalone
- [x] select voice on startup

**Comment by SmallTownSound** [comment]
I downloaded the update to studio One 5 professional, it does the same thing as on 4, it locks up the gui portion of studio One , but Studio One still does everything not related to the Vst' s GUI.  I tried this on both my laptop and my production desktop, and both act the same way.

Another thing I noticed it that when I drag a cart file to the GUI on the standalone, it moves the whole GUI to the left or right, or up or down in the GUI window during the drag about half the time.

Synergia isn't recognized by synergized on either of my computers, but I didn't work with the combination very long.

Still, the sound quality and accuracy of the internals and the carts is amazing.  Thanks for doing the Synergia. I have been waiting a long time for this.

Don

**Comment by SmallTownSound** [comment]
Synergia now connects to Synergized.  Had to go to the direct address of VRAM to connect, now no problems..  

AMAZING!

**Comment by jariseon** [comment]
unfortunately i've been so far unable to reproduce the Studio One issue. there's something different in our configurations. some hosts have a config option to run plugins either in-process or in a separate process.  i am new to Studio One, does it have such a setting, or any other idea what might be set up differently ? the gui is implemented as a webview.

here's what i did: installed Studio One Prime, and activated a 30-day Professional demo. then nuked my previous Synergia instance and installed a fresh one using the installer. booted up Studio One and dropped the plugin onto the workspace. the gui responded to mouse events.

![StudioOne](https://user-images.githubusercontent.com/10279461/98601840-4593c000-22e8-11eb-84ee-6d01b5de2aa0.png)

Studio One 5.1.0.61423
Windows 10 Home v2004 build 19041.572

**Comment by jariseon** [comment]
i was able to reproduce the drag'n'drop bug. thanks, will open a separate issue to track it.

**Comment by SmallTownSound** [comment]
Hmmm..   I did the same thing exactly, on both desktop & laptop, and had the same problem with no GUI.  I will try a S1 5 install that does not read current V4 install and see what happens.

**Comment by SmallTownSound** [comment]
OK uninstalled all setting for S1 V5, so it would start from scratch...  Reinstalled Synergia on my laptop (not screwing with important stuff on desktop DAW to test)....  It still does the same thing, no GUI appears, and GUI for second Vys will not show.
Tried on Reaper, it does the same thing, except if I Load synergia and another VST, Synergia will not show up, but the second one works...
Must be something else interfering with the 'Webview' of Synergia, since it does it on both computers.  Are you aware of any other VSTs setting up their GUI this way I can test?  I have never had this issue with any other vst in the 10+ years I have been using S1, since V2

**Comment by jariseon** [comment]
oh i thought it was working on Reaper. the missing gui might then be an effect instead of a cause: i was able to reproduce what you are seeing by renaming the support folder (which contains the roms etc) so that the plugin does not find it.

i do not yet understand though how that might happen as the standalone is able to find the folder. the support folder is located in C:/Users/<username>/AppData/Roaming/Synergia. i suppose if the plugin was installed using a different user account (eg. admin) than the one used for the daw session, the folder would not be there.

it could well be something else. need to think more. anyways, i am refactoring the plugin init code so that it does not hang if such a thing happens.

**Comment by SmallTownSound** [comment]
You found the problem!!!!   I run Studio One and Reaper in Admin mode, it solves a few drag & drop issues from outside of the DAW.  If I turn off Admin mode, Synergia loads fine!!!  :) 

I only have Admin & one user (STS) on the machine, but admin mode doesn't use STS....

You need to add a way to set the support folder location manually if Synergia can not find it.

Don

**Comment by jariseon** [comment]
cool! i'll open an issue to track the followup.
